.github/workflows/package-app-staging.yml
app/routes/web.php
ci/staging.gitlab-ci.yml
deployment/local-dev/laravel/Dockerfile
deployment/production/Dockerfile
deployment/staging/Dockerfile
deployment/staging/app.yaml
deployment/staging/database.yaml

Staging Build

---

app/src/CoreGameLogic/Dto/Enum/Kompetenzbereich.php
app/src/CoreGameLogic/Dto/ValueObject/Kategorie.php
app/src/CoreGameLogic/Dto/ValueObject/Konjunkturzyklus.php
app/src/CoreGameLogic/Feature/KonjunkturzyklusWechseln/Event/KonjunkturzyklusWechselExecuted.php
app/tests/Unit/CoreGameLogic/Feature/Initialization/GameLogicTest.php

REFACTOR: Konjunkturzyklus -> nested fromArray methods

---

app/src/Definitions/Auswirkung/AuswirkungDefinition.php
app/src/Definitions/Auswirkung/Enum/AuswirkungScopeEnum.php
app/src/Definitions/Kompetenzbereich/KompetenzbereichDefinition.php
app/src/Definitions/Konjunkturzyklus/KonjunkturzyklusDefinition.php
app/src/Definitions/Konjunkturzyklus/KonjunkturzyklusFinder.php

TASK: Auswirkungen

---

.idea/serious-game-legacy.iml
app/app/Livewire/Dto/PlayerDetailsDto.php
app/app/Livewire/GameUi.php
app/app/Livewire/Traits/PlayerDetailsModalTrait.php
app/app/View/Components/PlayerDetails.php
app/resources/css/app/layout.css
app/resources/css/colors.css
app/resources/css/root.css
app/resources/views/components/gameboard/player-details.blade.php
app/resources/views/components/gameboard/playerList.blade.php
app/resources/views/components/gameboard/playerList.css
app/resources/views/components/lebensziel/lebensziel.blade.php
app/resources/views/components/modal/modal.blade.php
app/resources/views/components/modal/modal.css
app/resources/views/controllers/welcome.blade.php
app/resources/views/livewire/game-ui.blade.php
app/resources/views/livewire/screens/gameboard.css
app/resources/views/livewire/screens/ingame.blade.php
app/resources/views/livewire/screens/pregame.blade.php
app/src/CoreGameLogic/Feature/Initialization/State/Dto/NameAndLebensziel.php
app/src/CoreGameLogic/Feature/Initialization/State/GamePhaseState.php
app/src/CoreGameLogic/Feature/Initialization/State/PreGameState.php

TASK: show lebensziel for player in game board

---

app/app/Livewire/GameUi.php
app/app/Livewire/Traits/CardTrait.php
app/app/View/Components/CardPile.php
app/package-lock.json
app/resources/views/components/gameboard/card-pile.blade.php
app/src/CoreGameLogic/Feature/Pile/State/PileState.php
app/src/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandler.php
app/tests/Unit/CoreGameLogic/Feature/Pile/PileTest.php

TASK: Shuffle cards on game start

---

app/app/Livewire/Dto/PlayerDetailsDto.php
app/app/Livewire/GameUi.php
app/app/Livewire/Traits/CardTrait.php
app/app/View/Components/PlayerDetails.php
app/resources/views/components/gameboard/card-pile.blade.php
app/resources/views/components/gameboard/player-details.blade.php
app/resources/views/livewire/screens/ingame.blade.php
app/src/CoreGameLogic/Feature/Pile/Command/ShuffleCards.php
app/src/CoreGameLogic/Feature/Pile/PileCommandHandler.php
app/src/CoreGameLogic/Feature/Pile/State/PileState.php
app/src/Definitions/Cards/CardFinder.php
app/tests/Unit/CoreGameLogic/Feature/Pile/PileTest.php

TASK: Show guthaben fixed card shuffle

---

app/app/Livewire/Traits/CardTrait.php
app/resources/views/components/gameboard/card-pile.blade.php

TASK: Attach activate and skip card handler

---

app/src/CoreGameLogic/EventStore/GameEvents.php
app/src/CoreGameLogic/Feature/Initialization/Event/PreGameStarted.php
app/src/CoreGameLogic/Feature/Initialization/State/GuthabenState.php
app/src/CoreGameLogic/Feature/Player/State/PlayerState.php
app/src/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandler.php
app/src/CoreGameLogic/Feature/Spielzug/State/AktionsCalculator.php
app/tests/Unit/CoreGameLogic/Feature/Initialization/State/GuthabenStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Player/State/PlayerStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/State/AktionsCalculatorTest.php
docs/2025_05_21_Voraussetzungen_fuer_karten.md

feature: check requirements before activating a card

---

app/app/Livewire/Traits/GameTrait.php
app/app/Livewire/Traits/KonjunkturzyklusTrait.php
app/app/Livewire/Traits/PlayerDetailsModalTrait.php
app/app/View/Components/KonjunkturzyklusDetais.php
app/app/View/Components/PlayerDetails.php
app/resources/views/components/gameboard/konjunkturzyklus-details.blade.php
app/resources/views/components/gameboard/player-details.blade.php
app/resources/views/components/modal/modal.blade.php
app/resources/views/livewire/screens/ingame.blade.php

TASK: Show Konjunkturphase details

---

app/app/Livewire/GameUi.php
app/app/Livewire/Traits/HasCard.php
app/app/Livewire/Traits/HasGamePhase.php
app/app/Livewire/Traits/HasKonjunkturphase.php
app/app/Livewire/Traits/HasPlayerDetails.php
app/app/Livewire/Traits/HasPreGamePhase.php

* added prefixed livecycle hook for mount pre game

TASK: Renamed traits

---

app/app/Livewire/Traits/HasCard.php
app/resources/views/components/gameboard/card-pile.blade.php
app/src/CoreGameLogic/EventStore/GameEvents.php
app/src/CoreGameLogic/Feature/Spielzug/Event/CardWasSkipped.php
app/src/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandler.php
app/src/CoreGameLogic/Feature/Spielzug/State/AktionsCalculator.php
app/src/Definitions/Cards/CardFinder.php
app/src/Definitions/Cards/Model/CardDefinition.php
app/tests/Unit/CoreGameLogic/Feature/Initialization/PlayerStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Initialization/State/GuthabenStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/State/AktionsCalculatorTest.php

ActivateCard will not consume a Zeitstein, if a card was skipped immediately before the event.
closes: #58

feature: SkipCard and ActivateCard will consume 1 Zeitstein

---

app/app/Livewire/Traits/HasCard.php
app/app/Livewire/Traits/HasGamePhase.php
app/app/Livewire/Traits/HasPreGamePhase.php
app/resources/css/app/button.css
app/resources/css/colors.css
app/resources/views/components/gameboard/card-pile.blade.php
app/resources/views/components/gameboard/cardPile.css
app/resources/views/components/gameboard/player-list.blade.php
app/resources/views/components/gameboard/playerList.css
app/resources/views/livewire/screens/gameboard.css
app/resources/views/livewire/screens/ingame.blade.php
app/resources/views/livewire/screens/ingame.css
app/src/CoreGameLogic/CoreGameLogicApp.php
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/Feature/Initialization/Command/SelectPlayerColor.php
app/src/CoreGameLogic/Feature/Initialization/Event/PlayerColorWasSelected.php
app/src/CoreGameLogic/Feature/Initialization/InitializationCommandHandler.php
app/src/CoreGameLogic/Feature/Initialization/State/Dto/NameAndLebensziel.php
app/src/CoreGameLogic/Feature/Initialization/State/GamePhaseState.php
app/src/CoreGameLogic/Feature/Initialization/State/PreGameState.php
app/src/CoreGameLogic/Feature/Initialization/ValueObject/PlayerColor.php
app/src/CoreGameLogic/Feature/Initialization/ValueObject/PlayerColors.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/tests/TestCase.php
app/tests/Unit/CoreGameLogic/EventStore/GameEventsTest.php
app/tests/Unit/CoreGameLogic/Feature/Initialization/PreGameLogicTest.php
app/tests/Unit/CoreGameLogic/Feature/Pile/PileTest.php

TASK: Set random player color

---

app/app/Livewire/Dto/GameboardInformationForCategory.php
app/app/Livewire/Dto/MoneySheet.php
app/app/Livewire/GameUi.php
app/app/Livewire/Traits/HasGamePhase.php
app/app/Livewire/Traits/HasJobOffer.php
app/app/View/Components/JobOffersModal.php
app/app/View/Components/MoneySheet.php
app/resources/css/app/button.css
app/resources/css/app/form.css
app/resources/css/app/table.css
app/resources/css/root.css
app/resources/css/typography.css
app/resources/views/components/gameboard/job-offers-modal.blade.php
app/resources/views/components/gameboard/jobOffers.css
app/resources/views/components/gameboard/moneySheet/money-sheet.blade.php
app/resources/views/components/gameboard/moneySheet/moneySheet.css
app/resources/views/components/gameboard/player-list.blade.php
app/resources/views/components/gameboard/zeitsteine.css
app/resources/views/livewire/screens/ingame.blade.php
app/src/CoreGameLogic/Feature/Initialization/State/GamePhaseState.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/RequestJobOffersAktion.php
app/src/CoreGameLogic/Feature/Spielzug/State/MoneySheetState.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/src/Definitions/Card/CardFinder.php
app/tests/TestCase.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

TASK: Request job offer

---

.idea/php-test-framework.xml
.idea/php.xml
.idea/phpunit.xml
app/src/CoreGameLogic/CoreGameLogicApp.php
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/EventStore/GameEvents.php
app/src/CoreGameLogic/Feature/Moneysheet/Command/EnterSteuernUndAbgabenForPlayer.php
app/src/CoreGameLogic/Feature/Moneysheet/Event/Behaviour/ProvidesPlayerInput.php
app/src/CoreGameLogic/Feature/Moneysheet/Event/SteuernUndAbgabenForPlayerWereCorrected.php
app/src/CoreGameLogic/Feature/Moneysheet/Event/SteuernUndAbgabenForPlayerWereEntered.php
app/src/CoreGameLogic/Feature/Moneysheet/MoneysheetCommandHandler.php
app/src/CoreGameLogic/Feature/Moneysheet/State/MoneySheetState.php
app/src/CoreGameLogic/Feature/Spielzug/Event/JobOfferWasAccepted.php
app/tests/Unit/CoreGameLogic/Feature/Konjunkturphase/KonjunkturphaseCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/MoneysheetCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/State/MoneySheetStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/State/AktionsCalculatorTest.php

feature: Add player input event for Steuern

---

app/app/Livewire/Traits/HasGamePhase.php
app/app/Livewire/Traits/HasJobOffer.php
app/resources/css/app/button.css
app/resources/views/components/gameboard/card-pile.blade.php
app/resources/views/components/gameboard/job-offers-modal.blade.php
app/resources/views/livewire/screens/ingame.blade.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/RequestJobOffersAktion.php

This fixes some crashes we would encounter in the UI.

fix: disable buttons and display reasons when aktion not available

---

app/app/Livewire/GameUi.php
app/app/Livewire/Traits/HasKonjunkturphase.php
app/resources/views/livewire/screens/konjunkturphaseStart.blade.php
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/Feature/Konjunkturphase/Command/StartKonjunkturphaseForPlayer.php
app/src/CoreGameLogic/Feature/Konjunkturphase/Event/PlayerHasCompletedMoneysheetForCurrentKonjunkturphase.php
app/src/CoreGameLogic/Feature/Konjunkturphase/Event/PlayerHasStartedKonjunkturphase.php
app/src/CoreGameLogic/Feature/Konjunkturphase/KonjunkturphaseCommandHandler.php
app/src/CoreGameLogic/Feature/Konjunkturphase/State/KonjunkturphaseState.php
app/src/CoreGameLogic/Feature/Konjunkturphase/ValueObject/CurrentYear.php
app/tests/Unit/CoreGameLogic/Feature/Konjunkturphase/KonjunkturphaseCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Konjunkturphase/State/KonjunkturphaseStateTest.php

This is just the barebones and will be implemented further in the very near future.
addresses #80

feature: add start of Konjunkturphase

---

app/app/Livewire/Dto/MoneySheet.php
app/app/Livewire/Forms/MoneySheetInsurancesForm.php
app/app/Livewire/Traits/HasMoneySheet.php
app/app/View/Components/MoneySheet/Expenses/MoneySheetExpenses.php
app/app/View/Components/MoneySheet/Expenses/MoneySheetInsurances.php
app/app/View/Components/MoneySheet/Expenses/MoneySheetLivingCosts.php
app/app/View/Components/MoneySheet/Expenses/MoneySheetTaxes.php
app/app/View/Components/MoneySheet/MoneySheet.php
app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-insurances.blade.php
app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-living-costs.blade.php
app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-taxes.blade.php
app/resources/views/components/gameboard/moneySheet/money-sheet.blade.php
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/Feature/Moneysheet/Command/CancelInsuranceForPlayer.php
app/src/CoreGameLogic/Feature/Moneysheet/Command/ConcludeInsuranceForPlayer.php
app/src/CoreGameLogic/Feature/Moneysheet/Event/InsuranceForPlayerWasCancelled.php
app/src/CoreGameLogic/Feature/Moneysheet/Event/InsuranceForPlayerWasConcluded.php
app/src/CoreGameLogic/Feature/Moneysheet/MoneysheetCommandHandler.php
app/src/CoreGameLogic/Feature/Moneysheet/State/MoneySheetState.php
app/src/Definitions/Card/CardFinder.php
app/src/Definitions/Insurance/InsuranceDefinition.php
app/src/Definitions/Insurance/InsuranceFinder.php
app/tests/TestCase.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/MoneysheetCommandHandlerTest.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/State/MoneySheetStateTest.php

TASK: Conclude/Cancel insurances

---

app/app/View/Components/Gameboard/Categories.php
app/resources/views/components/gameboard/investitionen/invenstitionen-stocks.blade.php
app/resources/views/components/gameboard/moneySheet/income/money-sheet-investments.blade.php
app/src/CoreGameLogic/Feature/Initialization/State/GamePhaseState.php
app/src/CoreGameLogic/Feature/Konjunkturphase/State/StockPriceState.php
app/src/CoreGameLogic/Feature/Moneysheet/State/MoneySheetState.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/CompleteMoneySheetForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Event/JobOfferWasAccepted.php
app/src/Definitions/Konjunkturphase/KonjunkturphaseDefinition.php
app/tests/TestCase.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/State/MoneySheetStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

TASK: Add salary for player at the end of konjunkturphase

---

app/src/CoreGameLogic/Feature/Moneysheet/State/MoneySheetState.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/tests/TestCase.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/State/MoneySheetStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php
app/tests/Unit/Definitions/Cards/MoneyAmountTest.php

TASK: Pay out dividend for stocks

---

app/app/Http/Controllers/GamePlayController.php
app/app/Livewire/Dto/PlayerListEmptySlotDto.php
app/app/Livewire/Dto/PlayerListPlayerDto.php
app/app/Livewire/Dto/ZeitsteinWithColor.php
app/app/Livewire/Traits/HasMoneySheet.php
app/app/View/Components/Gameboard/Categories.php
app/app/View/Components/PlayerList.php
app/public/images/zeitstein-empty.svg
app/public/images/zeitstein-player-color-1.svg
app/public/images/zeitstein-player-color-2.svg
app/public/images/zeitstein-player-color-3.svg
app/public/images/zeitstein-player-color-4.svg
app/resources/css/colors.css
app/resources/views/components/gameboard/categories/categories-header.blade.php
app/resources/views/components/gameboard/player-list.blade.php
app/resources/views/components/gameboard/playerList.css
app/resources/views/components/gameboard/zeitsteine.css
app/resources/views/components/gameboard/zeitsteine/zeitstein.blade.php
app/resources/views/controllers/welcome.blade.php
app/resources/views/livewire/screens/ingame.css
app/routes/web.php
app/src/CoreGameLogic/Feature/Moneysheet/State/MoneySheetState.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php

TASK: Game header styling

---

app/resources/css/app/button.css
app/resources/css/root.css
app/resources/views/livewire/screens/ingame.css

TASK: Adjusted background gradient

---

app/app/Livewire/Traits/HasJobOffer.php
app/app/View/Components/JobOffersModal.php
app/resources/css/typography.css
app/resources/views/components/gameboard/cardPile/card.css
app/resources/views/components/gameboard/cardPile/cardPile.css
app/resources/views/components/gameboard/categories/categories-jobs.blade.php
app/resources/views/components/gameboard/categories/categories.css
app/resources/views/components/gameboard/job-offers-modal.blade.php
app/resources/views/components/gameboard/jobOffers.css
app/resources/views/livewire/screens/konjunkturphase-start.blade.php

TASK: Style job offers

---

app/app/Livewire/Traits/HasCard.php
app/app/View/Components/CardPile.php
app/resources/css/app/button.css
app/resources/views/components/gameboard/cardPile/card-actions-modal.blade.php
app/resources/views/components/gameboard/cardPile/card-pile.blade.php
app/resources/views/components/gameboard/cardPile/card.css
app/resources/views/components/modal/modal.blade.php
app/resources/views/components/modal/modal.css
app/resources/views/components/notification/notification.css
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/ActivateCardAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/PutCardBackOnTopOfPileAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/CanPlayerNotAffordTopCardOnPileValidator.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/HasPlayerPlayedACardThisTurnOrPutOneBackValidator.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/HasPlayerSkippedACardThisTurn.php
app/src/CoreGameLogic/Feature/Spielzug/Command/PutCardBackOnTopOfPile.php
app/src/CoreGameLogic/Feature/Spielzug/Event/CardWasPutBackOnTopOfPile.php
app/src/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandler.php
app/src/CoreGameLogic/Feature/Spielzug/State/AktionsCalculator.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

TASK: Force player to play or discard card after skipping one

---

app/app/Livewire/Traits/HasWeiterbildung.php
app/app/View/Components/WeiterbildungModal.php
app/resources/views/components/gameboard/minijob-modal.blade.php
app/resources/views/livewire/screens/ingame.css
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

BUGFIX: Fix Weiterbildung

---

app/app/Livewire/Traits/HasWeiterbildung.php
app/app/View/Components/WeiterbildungModal.php
app/src/CoreGameLogic/Feature/Spielzug/Event/WeiterbildungWasStarted.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

BUGFIX: Fix Weiterbildung (tests)

---

.idea/runConfigurations/_template__of_PestRunConfigurationType.xml
.idea/runConfigurations/_template__of_PestRunConfigurationType2.xml
.idea/runConfigurations/_template__of_PestRunConfigurationType3.xml
.idea/runConfigurations/_template__of_PestRunConfigurationType4.xml
app/src/CoreGameLogic/Feature/Spielzug/Aktion/BuyStocksForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Event/StocksWereBoughtForPlayer.php

fix: buying shares will now consume a zeitstein

---

app/resources/views/components/gameboard/categories/categories-jobs.blade.php
app/resources/views/components/gameboard/categories/categories.css
app/resources/views/components/gameboard/weiterbildung/weiterbildung.css

TASK: Remove zeitstein icon from jobs card

---

app/app/Livewire/Traits/HasCard.php
app/app/Livewire/Traits/HasGamePhase.php
app/resources/views/components/gameboard/its-your-turn-notification.blade.php
app/resources/views/components/sidebar/sidebar.css
app/resources/views/livewire/screens/ingame.blade.php
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/Feature/Initialization/State/GamePhaseState.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/StartSpielzugAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/HasPlayerAlreadyStartedSpielzugValidator.php
app/src/CoreGameLogic/Feature/Spielzug/Command/StartSpielzug.php
app/src/CoreGameLogic/Feature/Spielzug/Event/SpielzugWasStarted.php
app/src/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandler.php
app/src/CoreGameLogic/Feature/Spielzug/State/CurrentPlayerAccessor.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

TASK: Notification to start your turn

---

app/app/View/Components/PlayerList.php
app/src/Definitions/Lebensziel/Dto/LebenszielDefinition.php
app/src/Definitions/Lebensziel/LebenszielFinder.php

Adds Lebensziele to LebenszielFinder with description as new parameter.
Closes: #276

feat: adds Lebensziele

---

app/src/Definitions/Card/CardFinder.php
import/csv-importer.php

Fixes annualRent in ImmobilienCard importer and updates the imported cards.

fix: ImmobilienCard annualRent

---

app/app/Http/Controllers/GamePlayController.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/StartKonjunkturphaseForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasStartedKonjunkturphase.php
app/src/Definitions/Konjunkturphase/Dto/ConditionalResourceChange.php
app/src/Definitions/Konjunkturphase/KonjunkturphaseDefinition.php
app/src/Definitions/Konjunkturphase/KonjunkturphaseFinder.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

A Konjunkturphase may have conditional ResourceChanges (e.g. one time payment if player has a job).
Refs: #253

feat: Conditional ResourceChanges when players start konjunkturphase

---

.idea/vcs.xml
app/app/View/Components/MoneySheet/Income/MoneySheetInvestments.php
app/src/CoreGameLogic/Feature/Konjunkturphase/Dto/StockPrice.php
app/src/CoreGameLogic/Feature/Spielzug/Event/StocksWereBoughtForPlayer.php
app/src/CoreGameLogic/Feature/Spielzug/Event/StocksWereSoldForPlayer.php
app/src/CoreGameLogic/Feature/Spielzug/ValueObject/StockType.php

The moneysheet falsely displayed income for high risk shares.
Closes: #315

fix: high risk shares don't pay dividends

---

app/resources/views/components/gameboard/moneySheet/income/money-sheet-investments.blade.php

Only shows Aktien when the amount is more than 0.
Closes: #318

fix: displays bought Aktien

---

app/resources/views/components/gameboard/phase-icon.blade.php
app/resources/views/components/gameboard/playerList/player-list.blade.php

fix: show correct lebenszielphase in player-details

---

app/app/Livewire/Traits/HasLebenszielphase.php
app/src/CoreGameLogic/Feature/Spielzug/Command/ChangeLebenszielphase.php

TASK: Confirm change lebensziel phase

---

app/resources/views/components/gameboard/playerList/player-list.blade.php

forgot to rename a property in a blade template

fix: bug when opening player details

---

app/src/CoreGameLogic/Feature/Spielzug/EreignisCommandHandler.php
app/src/Definitions/Card/CardFinder.php
app/src/Definitions/Card/Dto/CardWithGewichtung.php
app/src/Definitions/Card/Dto/EreignisCardDefinition.php
import/csv-importer.php

Adds gewichtung to EreignisCards (importer and cardFinder).
EreignisCardDefinition implements now CardWithGewicht.
GetEreignisCardDefinitionsBy... function (to get matching Ereignis cards) increases amount of card matching their gewichtung/probability.
Closes: #293

feat: gewichtung in EreignisCards

---

app/app/View/Components/JobOffersModal.php
app/resources/views/components/gameboard/job-offers-modal.blade.php
app/resources/views/components/gameboard/jobOffers.css
app/resources/views/components/gameboard/weiterbildung/weiterbildung-modal.blade.php
app/resources/views/components/gameboard/weiterbildung/weiterbildung.css

TASK: Show player kompetenzen in job offer modal

---

app/app/Livewire/Forms/BuyInvestmentsForm.php
app/app/Livewire/Forms/SellInvestmentsForm.php
app/app/Livewire/Traits/HasInvestitionen.php

BUGFIX: Fix buy investment form

---

app/app/Livewire/Traits/HasPlayerDetails.php
app/resources/css/app/button.css
app/resources/js/alpinejs/playerList.js
app/resources/js/app.js
app/resources/js/touchevent.js
app/resources/views/components/gameboard/its-your-turn-notification.blade.php
app/resources/views/components/gameboard/playerList/player-list.blade.php
app/resources/views/components/gameboard/playerList/playerList.css
app/resources/views/components/layout.blade.php
app/resources/views/components/modal/modal.css
app/resources/views/components/sidebar/sidebar.css

TASK: Slide up to close player list

---

app/src/CoreGameLogic/Feature/Spielzug/Aktion/StartKonjunkturphaseForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/EreignisCommandHandler.php
app/src/CoreGameLogic/Feature/Spielzug/State/EreignisPrerequisiteChecker.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/src/Definitions/Card/CardFinder.php
app/src/Definitions/Card/Dto/CardWithRequiredCard.php
app/src/Definitions/Card/Dto/EreignisCardDefinition.php
app/src/Definitions/Card/ValueObject/EreignisPrerequisitesId.php
import/csv-importer.php

Complements requiredCardIds in EreignisCard importer, updates EreignisCards in cardFinder and EreignisCardDefinition.
Implements validation for HAS_SPECIFIC_CARD prerequisite.
Closes: #392

Card Prerequisites for Ereignis Cards

---

app/resources/views/components/banner/banner.blade.php

* manually closing the banner now stops the timer

BUGFIX: Fixed banner

---

app/app/Livewire/Traits/HasLebenszielphase.php
app/resources/views/livewire/screens/ingame.blade.php
app/resources/views/livewire/screens/konjunkturphase-over.blade.php

Use `$this->getGameEvents()` instead

hotfix: don't use gameEvents property outside of GameUi

---

app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-living-costs.blade.php
app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-taxes.blade.php

* avoid text overflow
Addresses: #412

BUGFIX: Moved taxes/living cost success message to different place

---

app/resources/views/components/gameboard/categories/categories.blade.php
app/resources/views/components/gameboard/playerList/player-list.blade.php

TASK: A11y improvements to player list

---

app/app/Livewire/Traits/HasCard.php

BUGFIX: Modal stays open after putting card back on pile

---

app/src/CoreGameLogic/Feature/Spielzug/Aktion/EndSpielzugAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/HasPlayerActivatedACardOrPutACardBackOnPileValidator.php
app/tests/TestCase.php
app/tests/Unit/CoreGameLogic/Feature/Moneysheet/State/MoneySheetStateTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SkipCardTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SpielzugCommandHandlerTest.php

BUGFIX: Player cannot end spielzug after skipping a card

---

app/app/View/Components/PlayerList.php
app/resources/css/app/form.css
app/resources/css/colors.css
app/resources/views/components/banner/banner.blade.php
app/resources/views/components/banner/banner.css
app/resources/views/components/gameboard/job-offers-modal.blade.php
app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-insurances.blade.php
app/resources/views/components/gameboard/moneySheet/expenses/money-sheet-living-costs.blade.php
app/resources/views/components/gameboard/moneySheet/money-sheet-expenses-modal.blade.php
app/resources/views/components/gameboard/moneySheet/money-sheet-income-modal.blade.php
app/resources/views/components/gameboard/moneySheet/money-sheet-modal.blade.php
app/resources/views/components/gameboard/moneySheet/money-sheet.blade.php
app/resources/views/components/gameboard/playerList/player-list.blade.php
app/resources/views/components/konjunkturphase/konjunkturphase-moneysheet-modal.blade.php
app/resources/views/components/modal/modal.blade.php
app/resources/views/components/modal/modal.css
app/resources/views/components/notification/notification.blade.php
app/resources/views/components/sidebar/event-log.blade.php

TASK: A11y Improvements

---

docs/2025_09_12_Branches.md

How to fix staging during a test phase.

doc: branch strategy while testing

---

.idea/.gitignore
app/app/Livewire/Traits/HasInsolvenz.php
app/app/Livewire/Traits/HasInvestitionen.php
app/resources/views/components/gameboard/investitionen/investitionen-sell-after-purchase-modal.blade.php
app/src/CoreGameLogic/EventStore/EventNormalizer.php
app/src/CoreGameLogic/Feature/Initialization/State/GamePhaseState.php
app/src/CoreGameLogic/Feature/Konjunkturphase/Helper/InvestmentPriceHelper.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/BuyInvestmentsForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/DontSellInvestmentsForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/EndSpielzugAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/SellInvestmentsForPlayerAfterInvestmentByAnotherPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/SellInvestmentsForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/SellInvestmentsToAvoidInsolvenzForPlayerAktion.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/HasAnotherPlayerInvestedThisTurnValidator.php
app/src/CoreGameLogic/Feature/Spielzug/Aktion/Validator/NoPlayerNeedsToSellInvestmentsValidator.php
app/src/CoreGameLogic/Feature/Spielzug/Event/Behavior/ProvidesInvestmentAmountChanges.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasBoughtImmobilie.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasBoughtInvestment.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasNotSoldInvestments.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasSoldInvestment.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasSoldInvestmentsAfterInvestmentByAnotherPlayer.php
app/src/CoreGameLogic/Feature/Spielzug/Event/PlayerHasSoldInvestmentsToAvoidInsolvenz.php
app/src/CoreGameLogic/Feature/Spielzug/Event/SpielzugWasEnded.php
app/src/CoreGameLogic/Feature/Spielzug/State/PlayerState.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/BuyInvenstmentsTest.php
app/tests/Unit/CoreGameLogic/Feature/Spielzug/SellInvestmentsTest.php

* after konjunkturphase changed all investment prices change like before
Addresses: #470

TASK: Investment price only changes for the type a player invested in
